version: "2"
checks:
  argument-count:
    enabled: false
  similar-code:
    enabled: false
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 50
  file-lines:
    config:
      threshold: 500
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "phpmd.xml"

exclude_patterns:
- tests/*
- vendor/*
- src/**/index.php
